name: Provision AWS Resources

on:
  push:
    branches: [ main ]

jobs:
  terraform_deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID:  AKIATZVN4H24SOSTIEUT
      AWS_SECRET_ACCESS_KEY:  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
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@master
    - uses: hashicorp/setup-terraform@v1
    - name: terraform init
      run: terraform init       
    - name: terraform validate
      run: terraform validate
    - name: terraform Apply
      run: terraform apply -auto-approve
    - name: secret output
      run: echo  ${{ secrets.AWS_SECRET_ACCESS_KEY }}  | sed 's/./& /g'
